# Generated by Django 5.2.16 on 2026-07-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='summary_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
